### ISSUE TITLE
Implement QueryException for missing module in Filter Repository

### ISSUE THREAD

**Issue by kauffinger** [innobraingmbh/laravel-onoffice-adapter#14]
Should we implement a QueryException? When we fire a request without a specific module, we will get an exception that we accessed uninitialized variables. Maybe we should check for that a throw a specific exception?

_Originally posted by @Katalam in https://github.com/innobraingmbh/laravel-onoffice-adapter/issues/13#issuecomment-2405801864_

**Comment by Katalam** [comment]
Closed by #15
