### ISSUE TITLE
[Feature]: die and dump in query

### ISSUE THREAD

**Issue by Katalam** [innobraingmbh/laravel-onoffice-adapter#16]
### Describe the feature you'd like

Wrapping a query with dd seams to have an overwhelming amount of work, just to echo the output at this line. Adding a dd inside the query should die and dump after the query result is received

### Describe alternatives you've considered

-

**Comment by kauffinger** [comment]
further enhancements to the query could significantly improve development experience:
- a raw() function, which returns the raw json response from onoffice
- a rawRequest() function, which returns the raw json of the request that would have been sent to onoffice
